### ISSUE TITLE
Native class doesn't try to load DLL via temp location

### ISSUE THREAD

**Issue by gmerkin** [kohsuke/winp#26]
Native class doesn't try to load DLL via temp location and class loading just fails with java.lang.UnsatisfiedLinkError exception "Native Library %homepath%.jenkins\cache\jars\2C\winp.x64.C29A3A9FA89660FAA034AABD3B4E3E20.dll already loaded in another classloader".
Although there is a code for this purpose, it cannot be reached due to uncought exception.

Particularly it is a root cause of https://issues.jenkins-ci.org/browse/JENKINS-20913

**Comment by christ66** [comment]
@oleg-nenashev should this issue be closed since it's fixed?

**Comment by oleg-nenashev** [comment]
Yes

**Comment by antoxar** [comment]
Issue reproducible with slave version 3.36.


Jan 12, 2020 8:33:54 PM org.jvnet.winp.Native loadByUrl
WARNING: Failed to load DLL from static location
java.lang.UnsatisfiedLinkError: Native Library C:\jk\remoting\jarCache\44\winp.x64.BFFE30B3B50581290B1866EF8D48C609.dll already loaded in another classloader
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2456)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:767)
	at java.base/java.lang.System.load(System.java:1834)
	at org.jvnet.winp.Native.loadDll(Native.java:242)
	at org.jvnet.winp.Native.loadByUrl(Native.java:162)
	at org.jvnet.winp.Native.load(Native.java:124)
	at org.jvnet.winp.Native.<clinit>(Native.java:93)
	at org.jvnet.winp.WinProcess.enableDebugPrivilege(WinProcess.java:245)
	at hudson.util.ProcessTree$Windows.<clinit>(ProcessTree.java:701)
	at hudson.util.ProcessTree.get(ProcessTree.java:447)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1103)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1094)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by geerligs** [comment]
having same issue with remoting version 3.27:

Apr 22, 2020 8:42:05 AM org.jvnet.winp.Native loadByUrl
WARNING: Failed to load DLL from static location
java.lang.UnsatisfiedLinkError: Native Library C:\jenkins_ci\remoting\jarCache\44\winp.x64.BFFE30B3B50581290B1866EF8D48C609.dll already loaded in another classloader
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.jvnet.winp.Native.loadDll(Native.java:242)
        at org.jvnet.winp.Native.loadByUrl(Native.java:162)
        at org.jvnet.winp.Native.load(Native.java:124)
        at org.jvnet.winp.Native.<clinit>(Native.java:93)
        at org.jvnet.winp.WinProcess.enableDebugPrivilege(WinProcess.java:245)
        at hudson.util.ProcessTree$Windows.<clinit>(ProcessTree.java:701)
        at hudson.util.ProcessTree.get(ProcessTree.java:447)
        at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1103)
        at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1094)
        at hudson.remoting.UserRequest.perform(UserRequest.java:212)
        at hudson.remoting.UserRequest.perform(UserRequest.java:54)
        at hudson.remoting.Request$2.run(Request.java:369)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
        at java.lang.Thread.run(Thread.java:748)
