### ISSUE TITLE
org.jvnet.winp.WinpException: Failed to read environment variable - [JENKINS-30782]

### ISSUE THREAD

**Issue by oleg-nenashev** [kohsuke/winp#29]
According to the code, the getCmdLineAndEnvVars() command is unreliable on ~~newer~~ modern OS versions.

The last ReadProcessMemory command may fail:

```
	// Checking the read size is more likely to result in success than checking the BOOL that is
	// returned by ReadProcessMemory, on newer versions of Windows. That said, neither approach
	// is particularly reliable past Vista. This approach differs from checking the BOOL in that
	// it will succeed for partial reads that read _some_ data, where the other approach fails.
```

There are many usages of the command in WinP itself and in the dependent codebase like Jenkins ( [JENKINS-30782](https://issues.jenkins-ci.org/browse/JENKINS-30782)). Example of the log in Jenkins:

```
The error that I get is ERROR: Build step failed with exception
org.jvnet.winp.WinpException: Failed to read environment variable table error=299 at .\envvar-cmdline.cpp:201
at org.jvnet.winp.Native.getCmdLineAndEnvVars(Native Method)
at org.jvnet.winp.WinProcess.parseCmdLineAndEnvVars(WinProcess.java:126)
at org.jvnet.winp.WinProcess.getCommandLine(WinProcess.java:102)
at org.jvnet.winp.WinProcess.killRecursively(WinProcess.java:66)
at hudson.util.ProcessTree$Windows$1.killRecursively(ProcessTree.java:425)
at hudson.util.ProcessTree.killAll(ProcessTree.java:141)
at hudson.Proc$LocalProc.destroy(Proc.java:379)
at hudson.Proc$LocalProc.join(Proc.java:352)
at hudson.Launcher$ProcStarter.join(Launcher.java:389)
at hudson.tasks.Ant.perform(Ant.java:217)
at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
at hudson.model.Build$BuildExecution.build(Build.java:205)
at hudson.model.Build$BuildExecution.doRun(Build.java:162)
at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
at hudson.model.Run.execute(Run.java:1741)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:408
```

Proposals:

* Fix the failing ReadProcessMemory operation if possible
* Reduce the scope of the EnvVars usage, provide API for retrieving the CMD Line only
 * It won't help Jenkins, which terminates processes by using EnvVars filters (e.g. by BUILD_NUMBER env. var)

**Comment by oleg-nenashev** [comment]
Closing the issue since it is not possible to get such stacktrace anymore since 1.25. Instead of that one will get more diagnostics
