### ISSUE TITLE
Send Ctrl+C does not work on Windows 8.1

### ISSUE THREAD

**Issue by segrey** [kohsuke/winp#58]
Windows 8.1 Pro

When running manually:
![image](https://user-images.githubusercontent.com/607109/48339160-8bc1d480-e678-11e8-9601-6ec66767730b.png)

When running via Java API:
```
Exception in thread "main" org.jvnet.winp.WinpException: External Ctrl+C execution failed for process pid=1160. Ctrl+C process exited with code -1073741515: Failed to attach to the console (see the AttachConsole WinAPI call). error=0 at winp.cpp:59
	at org.jvnet.winp.Native.sendCtrlC(Native Method)
	at org.jvnet.winp.Native.sendCtrlC(Native.java:90)
	at org.jvnet.winp.WinProcess.sendCtrlC(WinProcess.java:93)
	at example.Main.main(Main.java:29)
```
See example project to reproduce: [stop-child-process.zip](https://github.com/kohsuke/winp/files/2571422/stop-child-process.zip).

**Comment by oleg-nenashev** [comment]
So it will require MVS redist to be installed. https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_install-winpc/msvcr120dll-missing/ef3bca56-3155-4383-ac99-d2a6ea262831 

It is a usual issue in MVS projects unfortunately, needs a fix ASAP

**Comment by segrey** [comment]
Suggested fix: PR https://github.com/kohsuke/winp/pull/59

**Comment by segrey** [comment]
Also affects Windows 10 installations on Mac with Boot Camp. Looks like it missing MSVCR120.dll as well.
https://youtrack.jetbrains.com/issue/WEB-36095
